version: '3.3'

services:
  nginx:
    container_name: qeep_nginx
    image: nginx:latest
    restart: always
    volumes:
      - "./docker/config/nginx/conf.d/default.vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/qeep"
    ports:
      - "80:80"
    links:
      - php
      - db
      - redis
    networks:
      - internal

  php:
    container_name: qeep_php
    build: ./docker/containers/fpm
    image: php:7.4-fpm
    restart: always
    command: php-fpm --allow-to-run-as-root
    expose:
      - 9000
    volumes:
      - "./:/var/www/qeep"
      - "./docker/config/fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "./docker/config/fpm/conf.d/memcached.ini:/usr/local/etc/php/conf.d/memcached.ini"
    links:
      - db
      - redis
      - memcached
    #  - composer
    networks:
      - internal
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1"
      PHP_IDE_CONFIG: "serverName=Docker"

  db:
    container_name: qeep_db
    image: mariadb:10.1
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/config/db/10-init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - ./docker/config/db/my.cnf:/etc/mysql/mariadb.conf.d/my.cnf
      - "./:/var/www/qeep"
    networks:
      - internal
    environment:
      MYSQL_DATABASE: "qeep"
      MYSQL_USER: "qeep"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Europe/Moscow

  redis:
    container_name: qeep_redis
    image: redis:4
    volumes:
      - redis-data:/data
    networks:
      - internal

  memcached:
    image: memcached:1.5
    container_name: qeep_memcached
    networks:
      - internal
    environment:
      TZ: Europe/Moscow

volumes:
  db-data:
  redis-data:

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.229.0/28